### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by akainth015** [MLH-Fellowship/kk-r1-orientation#2]
How is this repository licensed? We can take a look at [Choose a License](https://choosealicense.com) and decide what is an appropriate license for our project.

I feel that a simple and permissive license would be the best route for the project, but the bare minimum is that we are not responsible for any actions users take using the project.

**Comment by cqvu** [comment]
I think MIT License fits what we need fine https://choosealicense.com/licenses/mit/. Any other preference?
